# Generated by Django 3.0.13 on 2022-04-18 14:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('input', 'Input'), ('text', 'Text'), ('html', 'HTML'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'True / False'), ('url', 'Url'), ('email', 'Email'), ('file', 'File'), ('image', 'Image'), ('json', 'JSON')], max_length=50, verbose_name='Type')),
                ('splitter', models.CharField(blank=True, choices=[('newline', 'New line'), (',', 'Comma'), ('.', 'Dot'), (';', 'Semicolon'), (' ', 'Tab')], help_text='Доступно тільки для типів: text, input', max_length=10, null=True, verbose_name='Splitter')),
                ('value_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Input')),
                ('value_text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text')),
                ('value_html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='HTML')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Integer')),
                ('value_float', models.IntegerField(blank=True, null=True, verbose_name='Float')),
                ('value_bool', models.NullBooleanField(verbose_name='Boolean')),
                ('value_url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='site_config', verbose_name='File')),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='site_config', verbose_name='Image')),
                ('value_json', models.TextField(blank=True, max_length=10000, null=True, verbose_name='JSON')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'ordering': ['label'],
            },
        ),
    ]
