# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfield',
            name='splitter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Splitter'),
        ),
    ]
